name: Build manylinux wheels

on:
  workflow_dispatch:
    inputs:
      wip:
        description: 'Publish work in progress package.'
        required: false
        default: 'true'
      image:
        description: 'Manylinux image to use.'
        required: false
        default: 'manylinux2014_x86_64'

jobs:
  build_packages:
    runs-on: ubuntu-latest
    env:
      PLAT: ${{ github.event.inputs.image }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Pull images
      run: |
        docker pull multiarch/qemu-user-static
        docker pull quay.io/pypa/${{ github.event.inputs.image }}:latest

    - name: Set up QEMU
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Build wheels (wip)
      if: ${{ github.event.inputs.wip == 'true' }}
      run: |
        docker run --rm -e PLAT --workdir /github/workspace -v $GITHUB_WORKSPACE:/"/github/workspace" quay.io/pypa/${{ github.event.inputs.image }} /opt/python/cp38-cp38/bin/python ".github/manylinux.py"

    - name: Publish package to TestPyPI (wip)
      if: ${{ github.event.inputs.wip == 'true' }}
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: wheelhouse/
        repository_url: https://test.pypi.org/legacy/

    - name: Build wheels (release)
      if: ${{ github.event.inputs.wip == 'false' }}
      run: |
        docker run --rm -e PLAT --workdir /github/workspace -v $GITHUB_WORKSPACE:/"/github/workspace" quay.io/pypa/${{ github.event.inputs.image }} /opt/python/cp38-cp38/bin/python ".github/manylinux.py" --release

    - name: Publish package to TestPyPI (release)
      if: ${{ github.event.inputs.wip == 'false' }}
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN_RELEASE }}
        packages_dir: wheelhouse/
