#!/bin/bash

clang-format -i -style="{AccessModifierOffset: -4,
                         AlignEscapedNewlinesLeft: false,
                         AlignTrailingComments: true,
                         AllowShortFunctionsOnASingleLine: true,
                         AllowShortIfStatementsOnASingleLine: true,
                         AllowShortLoopsOnASingleLine: true,
                         AlwaysBreakTemplateDeclarations: true,
                         BinPackParameters: true,
                         BreakBeforeBinaryOperators: false,
                         BreakBeforeBraces: Allman,
                         BreakBeforeTernaryOperators: false,
                         BreakConstructorInitializersBeforeComma: true,
                         ColumnLimit: 100,
                         ConstructorInitializerAllOnOneLineOrOnePerLine: false,
                         Cpp11BracedListStyle: true,
                         IndentWidth: 4,
                         Language: Cpp,
                         MaxEmptyLinesToKeep: 2,
                         NamespaceIndentation: Inner,
                         SpaceBeforeAssignmentOperators: true,
                         SpaceBeforeParens: ControlStatements,
                         SpacesInAngles: true,
                         SpacesInCStyleCastParentheses: true,
                         SpacesInParentheses: false,
                         Standard: Cpp11,
                         TabWidth: 4,
                         UseTab: Never }" libclingcon/clingcon.h libclingcon/clingcon/*.h libclingcon/src/*.cpp app/main.cpp libclingcon/test/test/*.h libclingcon/test/src/*.cpp
