name: tests

on:
  - push
  - pull_request

jobs:
  build:
    name: clingcon ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.12"]
        include:
          - os: ubuntu-latest
            generator: "Ninja Multi-Config"
            environment-file: .github/test-environment-linux.yml
          - os: macos-latest
            generator: "Ninja Multi-Config"
            environment-file: .github/test-environment.yml
          - os: windows-latest
            generator: "Visual Studio 18 2026"
            environment-file: .github/test-environment.yml
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: ${{ matrix.environment-file }}
          condarc: |
            channel_priority: strict
            channels:
              - potassco/label/dev-20
              - conda-forge

      - name: print info
        run: |
          env
          micromamba info
          micromamba list
          python -m site

      - name: fix cffi
        if: runner.os == 'macOS'
        shell: bash -el {0}
        run: |
          pip install cffi --force

      - name: Configure
        run: |
          cmake -S . -B build -G "${{ matrix.generator }}" -DCLINGCON_BUILD_TESTS=On

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Test
        run: |
          ctest --test-dir build -C Release --output-on-failure

      - name: Install
        run: |
          cmake --install build --config Release
          clingcon --version
