name: Deploy win/mac wheels (wip)

on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, macos-10.15]
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install prerequisites
      run: |
        pip install --user cffi scikit-build cmake ninja twine
        pip install --user --extra-index-url https://test.pypi.org/simple/ clingo-cffi

    - name: Compile
      run: python .github/pipwinmac.py
      env:
        TWINE_NON_INTERACTIVE: True
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
